apiVersion: v1
kind: Service
metadata:
  name: {{ include "app-chart.fullname" . }}-backend
  labels:
    {{- include "app-chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  type: ClusterIP
  selector:
    {{- include "app-chart.backendSelectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: 3000
      targetPort: http
