apiVersion: v1
kind: Service
metadata:
  name: {{ include "app-chart.fullname" . }}-frontend
  labels:
    {{- include "app-chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  type: ClusterIP
  selector:
    {{- include "app-chart.frontendSelectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: 80
      targetPort: http
